CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Activities" (
    "Id" text NOT NULL,
    "ActionType" text NOT NULL,
    "Details" text NOT NULL,
    "UserEmail" text NOT NULL,
    "UserFullName" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Activities" PRIMARY KEY ("Id")
);

CREATE TABLE "AgriItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric NOT NULL,
    "Description" text NOT NULL,
    "Image" text NOT NULL,
    "OwnerEmail" text NOT NULL,
    CONSTRAINT "PK_AgriItems" PRIMARY KEY ("Id")
);

CREATE TABLE "CartItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ProductId" bigint NOT NULL,
    "ProductName" text NOT NULL,
    "Price" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "ImageUrl" text NULL,
    "Category" text NULL,
    "ProductType" text NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id")
);

CREATE TABLE "ChatMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SenderEmail" text NOT NULL,
    "ReceiverEmail" text NOT NULL,
    "Content" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id")
);

CREATE TABLE "Machineries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Price" numeric NOT NULL,
    "Image" text NOT NULL,
    "Condition" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Category" text NOT NULL,
    "Description" text NOT NULL,
    "OwnerEmail" text NOT NULL,
    CONSTRAINT "PK_Machineries" PRIMARY KEY ("Id")
);

CREATE TABLE "Orders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "TransactionId" text NOT NULL,
    "ShippingAddress" text NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "BirthDate" text NOT NULL,
    "Address" text NOT NULL,
    "Bio" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "JoinedDate" text NOT NULL,
    "Avatar" text NULL,
    "WishlistJson" text NOT NULL,
    "CartJson" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "WishlistItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ProductId" bigint NOT NULL,
    "ProductName" text NOT NULL,
    "Price" numeric NOT NULL,
    "ImageUrl" text NULL,
    "InStock" boolean NOT NULL,
    "Category" text NULL,
    CONSTRAINT "PK_WishlistItems" PRIMARY KEY ("Id")
);

CREATE TABLE "MachineriesMedia" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MachineryId" bigint NOT NULL,
    "Url" text NOT NULL,
    "PublicId" text NOT NULL,
    "MediaType" text NOT NULL,
    "IsPrimary" boolean NOT NULL,
    CONSTRAINT "PK_MachineriesMedia" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MachineriesMedia_Machineries_MachineryId" FOREIGN KEY ("MachineryId") REFERENCES "Machineries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "ProductName" text NOT NULL,
    "Price" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "ImageUrl" text NULL,
    "ProductType" text NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MachineriesMedia_MachineryId" ON "MachineriesMedia" ("MachineryId");

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514091343_i', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Orders" ADD "CustomerEmail" text NULL;

ALTER TABLE "Orders" ADD "CustomerName" text NULL;

ALTER TABLE "Orders" ADD "CustomerPhone" text NULL;

ALTER TABLE "Orders" ADD "DeliveryOtp" text NULL;

CREATE TABLE "Reviews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "ProductType" text NOT NULL,
    "UserId" text NOT NULL,
    "UserName" text NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516052025_UpdateOrderForDeliverySystem', '7.0.11');

COMMIT;

